name: dockerize-on-mtrain

on: 
  push:
    paths:
      - mtrain/**
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: hongdunegcp1
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Docker build
      - name: Docker push

