name: dockerize-on-mtrain

on:
  push:
    paths:
      - mnist_train/**
      - .github/workflows/dockerize.yml # yaml이 변경될 때도 workflow 실행되게
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: hongdunegcp1
          password: ${{ secrets.DOCKER_PASSWORD}} # secret 가져오기

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Docker build
        run: docker build -t hongdunegcp1/mtrain mnist_train

      - name: Docker push
        run: docker push hongdunegcp1/mtrain
